name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      LOG_LEVEL: INFO  # Example of setting an environment variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --cov

    - name: Run linting
      run: |
        source venv/bin/activate
        pylint plugins tests

    - #name: Upload test coverage
      #uses: codecov/codecov-action@v3
      #with:
       # token: ${{ secrets.CODECOV_TOKEN }}
