name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LOG_LEVEL: INFO  # Example of setting an environment variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ensure you have the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Ensure you have the latest version
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev libgirepository1.0-dev build-essential

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --cov

    - name: Run linting
      run: |
        source venv/bin/activate
        pylint plugins tests

    # Uncomment the following lines if you want to upload test coverage
    #- name: Upload test coverage
    #  uses: codecov/codecov-action@v3
    #  with:
    #    token: ${{ secrets.CODECOV_TOKEN }}
